spring.application.name=taskflow
spring.datasource.url=jdbc:postgresql://localhost:5432/taskflow_db
spring.datasource.username=hpuser
spring.datasource.password=NEWdb@321

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true